name: Prettier

on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.vue"
      - "**/*.json"
      - "**/*.css"
      - "**/*.scss"
      - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npm run lint

  prettier:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Prettier
        run: |
          npm run format
